### ISSUE TITLE
UTF-8 encoding missing?

### ISSUE THREAD

**Issue by Snuffsis** [justeat/NLog.StructuredLogging.Json#115]
Writing an application that fetches data from a swedish accounting software. They have their error messages in Swedish, this causes the error messages that we get to stored in the json output as the diamondquestionmark symbol instead of encoded character.
Using the <attribute encode="false"/> as suggested by standard NLog doesn't work, as attributes aren't allowed with structuredlogging. the encoding="UTF-8" property on the target doesn't help either.

Been looking around a bit, and see no mention of encoding in the documentation for structuredlogging either.

attaching the nlog.config file I have.
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    throwExceptions="true
    encoding="UTF-8">
    <extensions>
        <add assembly="NLog.StructuredLogging.Json" />
    </extensions>
    <targets>
        <target name="localError"
            xsi:type="File"
            fileName="${basedir}/logs/error/${shortdate}-error.json"
            encoding="UTF-8"
            layout="${structuredlogging.json}"
            maxArchiveFiles="90"/>
	<target name="localSuccess"
            xsi:type="File"
            fileName="${basedir}/logs/success/${shortdate}-success.json"
            encoding="UTF-8"
            layout="${structuredlogging.json}"
            maxArchiveFiles="90"/>
	</targets>
	<rules>
            <logger name="error"
                minlevel="Debug"
                writeTo="localError" />
	<logger name="success"
                minlevel="Debug"
		writeTo="localSuccess"/>
	</rules>
</nlog>
```

**Comment by AnthonySteele** [comment]
>  the error messages that we get to stored in the json output as the diamondquestionmark symbol instead of encoded character.

That looks like a bug. Needs a test around it to verify.

**Comment by AnthonySteele** [comment]
I have added some tests, and have not been able to reproduce this issue, unless the `FileTarget` object is missing the ` encoding="UTF-8"` setting and it's .NET full framework.  But it looks like that is set up correctly above.

Can you supply more details - which .NET version, and which NLog version are you using?

**Comment by Snuffsis** [comment]
I was target .net 4.7 with the latest NLog version.

After a bit more testing on my side and trying the program on another computer, it seems like the issue is a local one for my PC. As it worked as it should on the second computer without any encoding problems at all.

**Comment by AnthonySteele** [comment]
Good to know that you have worked around it. It might be that somewhere in the code, we should specify a locale or format, instead of getting a value from the machine? I don't know where though.
