### ISSUE TITLE
Add ability to log without parameters

### ISSUE THREAD

**Issue by cmannix** [justeat/NLog.StructuredLogging.Json#116]
Hi,

I'm trying to use this library to add structured logging to a project, but I've run into an issue when using it with the NLog "MappedDiagnosticsLogicalContext" functionality for adding context data to logs. This lets you define scoped (or global) key value pairs that can be added to all your log lines.

Quite often I find I'm adding several pieces of data to the log context, and for several logs within that context I have no need to add more data at the point of logging, as all the relevant data is in the context. Unfortunately, theres no overload for any of the "Extended*" methods that allows me to do this as far as I can tell. Using an empty object as the log properties gives me the log data I want, but that's not a great solution.

As an example:

```csharp
using NLog;
using NLog.StructuredLogging.Json;

namespace Console
{
    internal class Program
    {
        private static void Main()
        {
            var logger = LogManager.GetCurrentClassLogger();
            try
            {
                using (MappedDiagnosticsLogicalContext.SetScoped("ContextData", "ABC"))
                {
                    // Doesn't compile:
                    // logger.ExtendedInfo("Test context data - StructuredLogging, no log properties");
                    
                    logger.ExtendedInfo("Test context data - StructuredLogging, empty object", new { });
                    logger.ExtendedInfo("Test context data - StructuredLogging, with data", new { LocalData = "123" });
                    logger.Info("Test context data - nlog only");
                }
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                LogManager.Shutdown();
            }
        }
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema-->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="c:\temp\console-example-internal.log"
      internalLogLevel="Info" >


    <!-- the targets to write to -->
    <targets>
        <!-- write logs to file -->
        <target xsi:type="File" name="target1" fileName="c:\temp\console-example.log"
                layout="${structuredlogging.json}" />
        <target xsi:type="Console" name="target2"
                layout="${date}|${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}" />


    </targets>

    <!-- rules to map from logger name to target -->
    <rules>
        <logger name="*" minlevel="Trace" writeTo="target1,target2" />

    </rules>
</nlog>
```

Results in:
> {"TimeStamp":"2019-01-14T10:38:21.156Z","Level":"Info","LoggerName":"Console.Program","Message":"Test context data - StructuredLogging, empty object","CallSite":"Console.Program.Main","ContextData":"ABC"}
> {"TimeStamp":"2019-01-14T10:38:21.373Z","Level":"Info","LoggerName":"Console.Program","Message":"Test context data - StructuredLogging, with data","CallSite":"Console.Program.Main","LocalData":"123","ContextData":"ABC"}
> {"TimeStamp":"2019-01-14T10:38:21.379Z","Level":"Info","LoggerName":"Console.Program","Message":"Test context data - nlog only"}

Am I missing something here? If not would it be possible to add this feature please - happy to submit a PR for it if so, as I think it should pretty much just be a case of either adding a default value for the logProperties parameter, or perhaps tweaking the 'structuredlogging.json' layout to include the context properties when just using the original nlog methods?

**Comment by AnthonySteele** [comment]
You should be able to use `null` instead of `new {}` for the `logProperties`. But it could use a default maybe?

**Comment by cmannix** [comment]
Hi Anthony - yes, null works, thanks. 

ExtendedException actually already has a default value for the log properties of null, and looking through the code I can't see any obvious execution paths that would differ if the methods for the other levels were changed to match.

**Comment by AnthonySteele** [comment]
I think at the time it made sense to make that optional on `ExtendedException` since with an exception log there are many fields to be taken off the exception object, and sometimes that's all that needed. 

The `SetScoped` support came later, giving rise to the case that you have where there are no additional fields for a `ExtendedInfo`.

I have no objection to defaulting `logProperties`  to null on the other methods as well.

**Comment by AnthonySteele** [comment]
FYI, I have nothing else that I need to add after #126, so unless anything comes up, I will probably cut a version 3.0 release soon.
