### ISSUE TITLE
Cannot install package when targeting .NET Framework 4.5.1

### ISSUE THREAD

**Issue by renomx** [justeat/NLog.StructuredLogging.Json#154]
Hi!

I am trying to integrate your library to my project, however, when I run the command Install-Package NLog.StructuredLogging.Json I'm getting the following error:

> You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework

Is there an specific version targeting this version of the framework? An suggestions on how to trouble shoot this issue?

**Comment by AnthonySteele** [comment]
Currently we target Full framework `4.5.2` and `NetStandard 2.0`, so we don't support Full framework `4.5.1`

Options are for you to upgrade your project to   `4.5.2` or later, or the next version of `NLog.StructuredLogging.Json` to downgrade this version to `4.5`

**Comment by renomx** [comment]
Thank you for your response @AnthonySteele I'll try upgrading to 4.5.2

**Comment by AnthonySteele** [comment]
Released as `4.0.0-rc01`
https://www.nuget.org/packages/NLog.StructuredLogging.Json/4.0.0-rc01

As the name suggests, this it just a test to make sure that it all still works, and will be re-labelled 4.0.0 in about a week if all is well and there are no fther changes.
