### ISSUE TITLE
Failing test on Mac

### ISSUE THREAD

**Issue by josephwoodward** [justeat/NLog.StructuredLogging.Json#157]
Hi,

[This test](https://github.com/justeat/NLog.StructuredLogging.Json/blob/1613be4389e36648159be301ac67a92cfe7b6696/src/NLog.StructuredLogging.Json.Tests/Helpers/MapperExceptionLoggingTests.cs#L61) permanently fails when running on a Mac as a slightly different StackTrace format is generated.

Instead of the expected:

```csharp
"   at NLog.StructuredLogging.Json.Tests.Helpers.MapperExceptionLoggingTests.GenerateExceptionWithStackTrace()"
```
It generates

```csharp
"  at NLog.StructuredLogging.Json.Tests.Helpers.MapperExceptionLoggingTests.GenerateExceptionWithStackTrace ()"
```

**Possible options**

From my perspective the following options exist, so before doing the work I'd be interested in which one you think is more suitable:

1. The assertion does a start with, so grab the beginning of the stack trace and sanitise it (strip spaces in this case). This is my personal preference.

2. Conditionally assert against the expected based on the OS. eg:
```csharp
Assert.That(result["ExceptionStackTrace"], Does.StartWith(StrackTraceByOs()));
```

3. Do a `Contains` on the stack trace on the following string (excluding the parentheses):
```csharp
NLog.StructuredLogging.Json.Tests.Helpers.MapperExceptionLoggingTests.GenerateExceptionWithStackTrace
```
Personally I'm thinking 2 would be the best way forward.

**Comment by AnthonySteele** [comment]
So the difference is just a space before the `()`. That's odd, but also not a significant failure. I'm happy with any of these fixes. If the only difference is spacing, it seems simpler to do #1 sanitise the stack trace.

**Comment by josephwoodward** [comment]
@AnthonySteele It's the space between the parentheses and only two spaces at the start of the string. I'll go with .1 then.

**Comment by AnthonySteele** [comment]
Fixed now, I assume?

**Comment by josephwoodward** [comment]
Yes, this is good to be closed 👍
