### ISSUE TITLE
Timezones differ from NLog itself

### ISSUE THREAD

**Issue by Snuffsis** [justeat/NLog.StructuredLogging.Json#159]
I have noticed that there is a difference in how structuredlogging makes the timestamp as opposed to NLOG itself.

I am NLogs own structured logging for logging locally, which creates a timestamp that follows the local computers locale and timezone.
example:
`{ "Timestamp": "2019-07-19 01:00:13.3124", "Level": "Info", "CallSite": "xxx", "LoggerName": "xxx", "Message": "xxx", "Status": "OK", ... }`

Then I am using structuredlogging.json layout for logging over webservice, which causes the timestamp to show the timestamp in the wrong timezone
example:
`{ "Timestamp": "2019-07-18 23:59:13.3124", "Level": "Info", "CallSite": "xxx", "LoggerName": "xxx", "Message": "xxx", "Status": "OK", ... }`

Basically, NLog seem to use the PCs local time, while structuredlogging is using UTC all the time.
Is it possible to make structuredlogging.json use the same timestamp as nlog?

This is my current nlog.config:

`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoreload="true"
      internalLogLevel="Debug"
      internalLogFile="debug.txt">

	<extensions>
		<add assembly="NLog.StructuredLogging.Json" />
	</extensions>

	<variable name="log_dir" value="${basedir}/logs"/>
        <variable name="archive_dir" value="${basedir}/archive"/>
	<variable name="human_readable_layout" value="${longdate}|${level}|${logger}|${message}|${onexception:EXCEPTION OCCURRED\:${exception:format=type,message,method,stackTrace:maxInnerExceptionLevel=5:innerFormat=shortType,message,method,stackTrace}}" />

	<targets async="true">
		<target name="log_json"
						xsi:type="File"
						fileName="${log_dir}/${level:lowercase=true}/${shortdate}.json"
						encoding="utf-8"
						archiveEvery="Day"
						archiveNumbering="Date"
						archiveDateFormat="yyyyMMdd"
						archiveFileName="${archive_dir}\{#####}-${level:lowercase=true}.log"
						concurrentWrites="false"
						keepFileOpen="false"
						maxArchiveFiles="90">
			<layout xsi:type="JsonLayout"
              includeAllProperties="true"
              maxRecursionLimit="5">
				<attribute name="Timestamp"
                   layout="${longdate}"/>
				<attribute name="Level"
                   layout="${level}"/>
				<attribute name="CallSite"
                   layout="${callsite}"/>
				<attribute name="LoggerName"
                   layout="${logger}"/>
				<attribute name="Message"
                   layout="${message}"/>
			</layout>
		</target>
		<target name="logstash"
            xsi:type="WebService"
            protocol="JsonPost"
            encoding="UTF-8"
            url="http://xxx">
			<parameter name="message" type="System.String" layout="${structuredlogging.json}"/>
			<header name="Authorization" layout="${Authentication}"/>
		</target>
	</targets>
	<rules>
		<logger name="*"
						minlevel="Info"
						writeTo="log_json"/>

		<logger name="*"
						minlevel="Debug"
						writeTo="logstash"/>
	</rules>
</nlog>`

**Comment by snakefoot** [comment]
Think UTC-time is the correct time-zone when doing Json.

Why not change this:

`<attribute name="Timestamp" layout="${longdate}"/>`

Into this:

`<attribute name="Timestamp" layout="${longdate:universalTime=true}"/>`

Or rename "Timestamp" into "LocalTimestamp" to make it obvious that it is not UTC-time.
