### ISSUE TITLE
Changing JsonSerializerSettings EG. CamelCasePropertyNames

### ISSUE THREAD

**Issue by cristianmercado19** [justeat/NLog.StructuredLogging.Json#161]
I would like to serialize all the property names in camelCase instead of PascalCase which is the default.

I could not get a workaround maybe because of the design in `ConvertJson` class.

```c#
    public static class ConvertJson
    {
        private static readonly JsonSerializerSettings LogSettings = new JsonSerializerSettings
        {
            ContractResolver = new DefaultContractResolver(),
            Formatting = Formatting.None
        };

        public static string Serialize(Dictionary<string, object> data)
        {
            return JsonConvert.SerializeObject(data, LogSettings);
        }
    }
```
I am not able to do...
`ContractResolver = new CamelCasePropertyNamesContractResolver(),`

Is there any way to do that?

Update: I do not want to change the original code of the library, I am looking for a way to extend it.
In the Unit Tests associated with, I explicitly have ignored the global setting

Class: `ConvertJsonTests`
Test: `SerialisationIsNotAffectedByChangeToGlobalSettings`

**Comment by snakefoot** [comment]
Maybe something like this:

```c#
        private static readonly JsonSerializerSettings LogSettings = new JsonSerializerSettings
        {
            ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new CamelCaseNamingStrategy()
            },
            Formatting = Formatting.None
        };
```

**Comment by cristianmercado19** [comment]
Hi @snakefoot , 

Although that could fix the issue, it is not a valid solution for me due to the fact that I do not want to change the original code which will force me to fork it.

I found it hard to extend.

**Comment by snakefoot** [comment]
Thought the question was how to make it camel-case.


Extending this library to allow override of JsonSerializer will probably require you to create a pull request.


The sad news is that this project seems to be in maintenance mode. Not much activity here.
