### ISSUE TITLE
Q: Structured logging with newer NLog

### ISSUE THREAD

**Issue by Peperud** [justeat/NLog.StructuredLogging.Json#162]
Newer NLog advertises structured logging on it own. 
Is NLog.StructuredLogging.Json still relevant then?

**Comment by snakefoot** [comment]
NLog.StructuredLogging.Json is like a fixed JsonLayout. Gives predictable output, and can be easily added to any project using nuget-package.

But yes JsonLayout gives much more freedom and customization.
