### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/NLog.StructuredLogging.Json#3]
.a version of this lib with Net core support would open some doors for us.
it's probably a lot harder to get the tests onto core, but also less important.

**Comment by martincostello** [comment]
I've got a fork of the _code_ ported to .NET Core in a .NET Core project, but because of that it doesn't have the project system updates (it also doesn't have the ported tests because NUnit dependencies).

**Comment by AnthonySteele** [comment]
Hi 

At some stage we are going to have to take a view for this project, JustSaying and others on whether we wait for NUnit to come to .Net core, or we port a lot of tests to XUnit. This is not trivial as there are lots of tools layered on top of NUnit.

In the meantime, can we avoid that, and get the main benefit of going to .Net core by porting `NLog.StructuredLogging.Json` but not `NLog.StructuredLogging.Json.Tests`, [using multiple targets like in JustSaying main project](https://github.com/justeat/JustSaying/blob/develop/JustSaying.AwsTools/project.json#L43) and [one target in the tests](https://github.com/justeat/JustSaying/blob/develop/JustSaying.AwsTools.UnitTests/project.json#L52)? 

In this arrangement you can use the project system updates and NUnit.

**Comment by slang25** [comment]
btw I have also ported this leaving the tests targeting the full framework. The only issue I have is I've had to drop CallSite because they have dropped support for `new StrackTrace()`. Did you find the same thing @martincostello? and how did you handle it?

**Comment by martincostello** [comment]
@slang25 Yeah I found the same. I can't remember what I did with it off the top of my head. I found an issue in the Core repo about them maybe bringing it back, but that'd be a while away yet.

**Comment by martincostello** [comment]
@slang25 So I did this, basically moving the call into the `if` block and changing the constructor.

``` csharp
if (ex != null)
{
    log.Exception = ex;
    log.Properties.Add("ExceptionIndex", exceptionIndex);
    log.Properties.Add("ExceptionCount", exceptionCount);

    if (!string.IsNullOrEmpty(tag))
    {
        log.Properties.Add("ExceptionTag", tag);
    }

    var stackTrace = new StackTrace(ex, false);
    log.SetStackTrace(stackTrace, StackHelper.IndexOfFirstCallingMethod(stackTrace.GetFrames()));
}
```

**Comment by AnthonySteele** [comment]
The NLog team comments on the issue is here: https://github.com/dotnet/corefx/issues/1797#issuecomment-185408376

I agree that a logging framework without stack traces is lacking a key feature.  :disappointed: 

Is it useful to get the rest of it working on .net core? Maybe with an #ifdef around the call stack, pending .Net core and NLog support for this?

**Comment by martincostello** [comment]
Are we just using `SetStackTrace()` to hide our code from the log stack traces? Or are we using it to add a stack trace when there would otherwise not be one? If it's the former, then there's other ways to skin the same cat by registering this assembly as a hidden assembly.

We could do try the `#ifdef` route though.

**Comment by AnthonySteele** [comment]
It's the latter, we use it to get a call site where otherwise we would not have one. We also use it where there is an exception, since the callsite where the exception (or other message) is logged is a different thing from the stack trace of where the exception was thrown.

**Comment by slang25** [comment]
Cool, that matches my understanding @AnthonySteele @martincostello. I have a bunch of failing tests that I will not be able to pass without `#ifdef`ing, but I think that's the right thing to do here. We are looking to enrich the log with the call stack of where the entry was logged.

Microsoft are saying people shouldn't rely on the StackTrace for any sort of logic (which we aren't) as it is an implementation detail that could change as a result of runtime optimisation, and increasing is becoming less useful, if you look at an async callstack it no longer represents a simple path of causality which is the thing you typically want.

It feels like there is a gap here today (with .NET Standard/Core and up) that needs filling, they will likely extend caller info attributes to include more details such as line number, but this still doesn't cover it. Regardless, this will be a gap felt by all logging frameworks for medium term.

I'll create an INCLUDE_CALLSITE compilation symbol and see how it goes.

**Comment by 304NotModified** [comment]
> I agree that a logging framework without stack traces is lacking a key feature

Is there someone would could help me in adding the stack trace API to .NET core?  Or helping in motivating others to write it ;)

**Comment by AnthonySteele** [comment]
Sorry, I was conflating two related things:

1) When **an exception** is logged, the exception has a full call stack indicating where it was thrown. We have this and we record it; and it also works on .Net core.

2) When **anything** is logged, exception or not, we record the `CallSite` where it is logged.  For an exception, the place in the code where it was logged can be quite different to the place where it was thrown.

We don't use the whole stack trace, just the first class and method name in the call stack above the logging library code.  But we use `new StackTrace()` to get this; and so it doesn't work on .Net core yet 😞

**Comment by martincostello** [comment]
Is this done now then?

**Comment by AnthonySteele** [comment]
It is getting close to done!

**Comment by AnthonySteele** [comment]
I think we're in the clear now. Will update when there's a .Net standard 2.0 and a version of Nlog that targets it.
