### ISSUE TITLE
Two Layouts

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/NLog.StructuredLogging.Json#34]
We have `StructuredLoggingLayoutRenderer` for when a layout renderer is appropriate.
When a layout is appropriate, we have `FlattenedJsonLayout` and `JsonWithPropertiesLayout`. Do we need both, and if so, when do you choose between them? Are the differences between them just history, and can they be made more similar?

**Comment by AnthonySteele** [comment]
The attibutes in `FlattenedJsonLayout` use a `LayoutRenderer` via a `JsonEncodeLayoutRendererWrapper`, while the properties in `JsonWithPropertiesLayout` use a `Layout`. I don't know what difference this makes yet.

**Comment by martincostello** [comment]
@AnthonySteele Did #35 resolve this?

**Comment by AnthonySteele** [comment]
The layouts share code and both have good robustness.
But there are still 2.

**Comment by AnthonySteele** [comment]
The reason for having 2 of them is, I think, here: https://github.com/justeat/NLog.StructuredLogging.Json#logging-additional-json-properties
