### ISSUE TITLE
Context, attaching properties

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/NLog.StructuredLogging.Json#52]
This is just speculation, nothing concrete yet.

The more that we deal with flowing state as context down to lower callees, the more that it seems a bad idea. I mean mainly `HttpContext`, `LogicalThreadContext` and `SynchronisationContext`

e.g. in a MVC controller, a database repository class is invoked, which logs a message about the database operation. It is very useful for business reasons to attach to this message a correlation Id read from http request headers. But for Software SRP reasons, it is better if the http request is only used in the controller that receives it. Use of `HttpContext.Current.Request.Headers` deep in the call stack or in some logging plugin is not ideal.

Is it possible to do some sort of way of reading values into the logger up the call stack, and automatically attaching them to everything logged below? e.g.

```csharp
var myCorrelationId = ReadItFromTheHttpHeaders(request);
using (logger.AddValue("CorrelationId", myCorrelationId))
{
   var results = await _repo.GetResults(id);
}
````
And all structured  logging inside that block will automagically get the property `"CorrelationId"` populated.

It would be easy to do this if there is only one request at a time. Hard to do it with concurrent requests. Or is this not possible without re-inventing context as a logging context?

**Comment by martincostello** [comment]
Yeah, using ```HttpContext.Current.Request.Headers``` deep down can be problematic. We've had issues in ASP.NET with race conditions with multiple parallel HTTP calls _eventually_ calling through to get headers via abstractions and creating...interesting results.

**Comment by AnthonySteele** [comment]
Is [MDLC](https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer) appropriate for this? It's a context, but if we don't have to write it from scratch, might be worth looking into. How would you read all the items out of the MDLC?

**Comment by AnthonySteele** [comment]
[MDLC](https://github.com/NLog/NLog/blob/master/src/NLog/MappedDiagnosticsLogicalContext.cs) seems to be basically a wrapper over [Logical call context](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.callcontext.logicalgetdata), and it exposes both gets and sets, so it seems usuable in this case. The question is if/how you want to to work for the user of StructuredLogging.

Is it affected by async hacks like setting current sync context to null?

I think that e.g. taking Correlation if from the htttp request and putting it onto a logging context in a controller action is a good idea, if it means that the htttp request context is not needed further down the call stack.
