### ISSUE TITLE
Scoped logs

### ISSUE THREAD

**Issue by oformaniuk** [justeat/NLog.StructuredLogging.Json#62]
Hi all,

After I saw #52 (Context, attaching properties) I got another idea how logs can be improved. It is related mostly to tracing logs, meaning providing better idea on the context of log message by attaching some unique ID (this also can be used to attach other properties if it is useful).

To achieve this we can wrap [`NestedDiagnosticsLogicalContext`](https://github.com/NLog/NLog/blob/master/src/NLog/NestedDiagnosticsLogicalContext.cs) of NLog.
I see it by using next syntax:
```csharp
using(Logger.BeginScope("first scope description", firstLogProps)) // first scope, Guid 5D646242-C5A3-4FA0-9A7A-779ED5EA56E2
{
  Logger.ExtendedInfo("scoped log", innerLogProps); // first message
  using(Logger.BeginScope("second scope description", secondLogProps)) // second scope, Guid 74253AC8-11BB-4CBD-B68D-ED966DBDB478
  {
    Logger.ExtendedInfo("scoped log", null); // second message
    using(Logger.BeginScope("third scope description", thirdLogProps)) // third scope, Guid 0721B91D-4764-4693-99D9-1AF4B63463A0
    {
      Logger.ExtendedInfo("scoped log", null); // third message
    }
  }
}
```
Each scope start and end logs. 
Not sure if logProps of scope should be attached to each message in it. (maybe it should be optional?)
And in properties we get something like this:
- For first message:
```javascript
  "ScopeId":"5D646242-C5A3-4FA0-9A7A-779ED5EA56E2", // first scope GUID
  "Stack":"5D646242-C5A3-4FA0-9A7A-779ED5EA56E2"
```
- For second message:
```javascript
  "ScopeId":"74253AC8-11BB-4CBD-B68D-ED966DBDB478", // second scope GUID
  "Stack":"5D646242-C5A3-4FA0-9A7A-779ED5EA56E2 -> 74253AC8-11BB-4CBD-B68D-ED966DBDB478" // first scope GUID -> second scope GUID
```
- For third message:
```javascript
  "ScopeId":"0721B91D-4764-4693-99D9-1AF4B63463A0", // third scope GUID
  "Stack":"5D646242-C5A3-4FA0-9A7A-779ED5EA56E2 -> 74253AC8-11BB-4CBD-B68D-ED966DBDB478 -> 0721B91D-4764-4693-99D9-1AF4B63463A0" // first scope GUID -> second scope GUID -> third scope GUID
```
The we can have hext query in Kibana, for example:
```javascript
{
  "query": {
    "wildcard": {
      "Stack": {
        "value": "*74253AC8-11BB-4CBD-B68D-ED966DBDB478*" // second scope GUID
      }
    }
  }
}
```
Query returns all log messages that are nested under second scope (in this case second and third messages).

**Comment by AnthonySteele** [comment]
I keep learning more about Nlog's features. This is a good one.

Are there docs on `NestedDiagnosticsLogicalContext` ? Does it work like MDLC, and if so should StructuredLogging be reading values out of it anyway?

Is this proposal like [Serilog's `ForContext` operation](https://github.com/serilog/serilog/wiki/Writing-Log-Events) ?

**Comment by oformaniuk** [comment]
I was not able to find any specific docs on `NestedDiagnosticsLogicalContext` except of source code on GitHub.

Yes, it works pretty similar to [MappedDiagnosticsLogicalContext](https://github.com/NLog/NLog/blob/master/src/NLog/MappedDiagnosticsLogicalContext.cs) that is currently used for Context purposes but approach of retreaving data may be different, but yes StructuredLogging should read values out of it.

Yes, the idea is to achieve something like in example.

**Comment by oformaniuk** [comment]
@AnthonySteele 
According to changes in your comment, no, it is more like in the [topic you've mentioned before](https://nblumhardt.com/2016/11/ilogger-beginscope/). Instead of using variable provided with `BeginScope`, it is transparent to users of the code and everything is handled inside.

**Comment by oformaniuk** [comment]
I would be glad if you check the way I see how this could be implemented in #67 pull request.

**Comment by martincostello** [comment]
@AnthonySteele Did #67 complete this?

**Comment by AnthonySteele** [comment]
Done
