### ISSUE TITLE
Package metadata

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/NLog.StructuredLogging.Json#8]
Package metadata at https://www.nuget.org/packages/NLog.StructuredLogging.Json/ is not quite right
- link to github project page - done
- depend on `NLog`
- update authors - done

**Comment by martincostello** [comment]
We should also have a proper icon for the package, instead of the default NuGet one.

**Comment by AnthonySteele** [comment]
I am going to close this, and raise a separate issue for the "depend on NLog" item.
Logo can be a separate issue as well.

**Comment by AnthonySteele** [comment]
See https://github.com/justeat/NLog.StructuredLogging.Json/issues/18 for the "depend on NLog"  item
